#!/usr/bin/env python3
"""
Metallic Glass D₂ Validation Visualization
Generated by Qwen 2.5 Coder - 2025-11-30

Validates DFA prediction: D₂ = 19/13 = 1.4615
Against experimental data: D₂ = 1.46 ± 0.06 under 500 MPa stress
"""
import matplotlib.pyplot as plt
import numpy as np

# Data for plotting
states = ['Rest', 'Stressed (500 MPa)', 'Pre-failure']
d2_rest = [2.3, 2.5]
d2_stressed = 1.46
d2_stressed_error = 0.06
d2_prefailure = [1.1, 1.2]

# Create figure and axis
fig, ax = plt.subplots(figsize=(10, 6))

# Plotting rest state as a range/bar
ax.plot([0, 0], d2_rest, color='blue', linewidth=3, label='Rest')
ax.fill_betweenx(d2_rest, -0.1, 0.1, color='lightblue', alpha=0.5)

# Plotting stressed state with error bars
ax.errorbar(1, d2_stressed, yerr=d2_stressed_error, fmt='o', color='red',
            markersize=10, capsize=5, capthick=2, label='Stressed (500 MPa)')

# Plotting pre-failure state as a range/bar
ax.plot([2, 2], d2_prefailure, color='green', linewidth=3, label='Pre-failure')
ax.fill_betweenx(d2_prefailure, 1.9, 2.1, color='lightgreen', alpha=0.5)

# Draw horizontal dashed line for DFA prediction
dfa_prediction = 19 / 13
ax.axhline(y=dfa_prediction, color='black', linestyle='--', linewidth=2,
           label=f'DFA Prediction (D₂ = 19/13 = {dfa_prediction:.4f})')

# Annotation showing predicted and observed values
annotation_text = f"Predicted: {dfa_prediction:.4f}\nObserved: {d2_stressed} ± {d2_stressed_error}"
ax.annotate(annotation_text, xy=(1, d2_stressed), xytext=(1.5, 1.8),
            fontsize=10, bbox=dict(boxstyle='round', facecolor='wheat'),
            arrowprops=dict(facecolor='black', shrink=0.05))

# Add validation box
validation_text = f"D₂ = 19/13 = {dfa_prediction:.4f}\nis within {d2_stressed} ± {d2_stressed_error}\n✓ VALIDATED"
ax.text(0.02, 0.98, validation_text, transform=ax.transAxes, fontsize=11,
        verticalalignment='top', bbox=dict(boxstyle='round', facecolor='lightgreen', alpha=0.8))

# Labels and title
ax.set_xlabel('State', fontsize=12)
ax.set_ylabel('Correlation Dimension D₂', fontsize=12)
ax.set_title('DFA Prediction D₂ = 19/13 Validated in Metallic Glass Under Stress', fontsize=14)

# Set x-ticks
ax.set_xticks(range(len(states)))
ax.set_xticklabels(states, fontsize=11)

# Set y-axis range
ax.set_ylim(0.8, 2.8)

# Show legend
ax.legend(loc='upper right')

# Add grid
ax.grid(True, alpha=0.3)

# Print validation statement
print("=" * 60)
print("DFA PREDICTION VALIDATED - D₂ = 19/13 within experimental error")
print("=" * 60)
print(f"\nDFA Prediction:  D₂ = 19/13 = {dfa_prediction:.6f}")
print(f"Observed Value:  D₂ = {d2_stressed} ± {d2_stressed_error}")
print(f"Range:           [{d2_stressed - d2_stressed_error}, {d2_stressed + d2_stressed_error}]")
print(f"Prediction in range: {d2_stressed - d2_stressed_error <= dfa_prediction <= d2_stressed + d2_stressed_error}")
print("\n✓ DFA prediction falls within experimental error bars")

# Display plot
plt.tight_layout()
plt.savefig('/home/king/Downloads/documentsforgi/evidence/metallic_glass_d2_validation.png', dpi=150)
print(f"\nPlot saved to: evidence/metallic_glass_d2_validation.png")
plt.show()
