#!/usr/bin/env python3
"""
Tension-Driven Mutation Simulation
Generated by Qwen 2.5 Coder - 2025-11-30

Tests the DFA hypothesis that mutation rate depends on S-R tension:
- T = |S - R| / (S + R)
- μ = μ_base × (1 + α × T²)
"""
import numpy as np
import matplotlib.pyplot as plt

class Agent:
    def __init__(self, S=None, R=None):
        self.S = S if S is not None else np.random.rand()
        self.R = R if R is not None else np.random.rand()

    def tension(self):
        if self.S + self.R == 0:
            return 0
        return abs(self.S - self.R) / (self.S + self.R)

    def fitness(self):
        return 1 - self.tension()

    def mutate(self, mutation_rate_base, alpha, variable_mutation=True):
        if variable_mutation:
            T = self.tension()
            mutation_rate = mutation_rate_base * (1 + alpha * T**2)
        else:
            mutation_rate = mutation_rate_base

        if np.random.rand() < mutation_rate:
            self.S = np.clip(self.S + np.random.normal(0, 0.1), 0, 1)
        if np.random.rand() < mutation_rate:
            self.R = np.clip(self.R + np.random.normal(0, 0.1), 0, 1)

def simulate(group_size, generations, mutation_rate_base, alpha, variable_mutation=True):
    agents = [Agent() for _ in range(group_size)]
    avg_fitnesses = []
    surplus_retentions = []
    adaptation_speeds = []

    for gen in range(generations):
        # Mutate
        for agent in agents:
            agent.mutate(mutation_rate_base, alpha, variable_mutation)

        # Calculate fitness
        fitnesses = [agent.fitness() for agent in agents]
        avg_fitness = np.mean(fitnesses)
        avg_fitnesses.append(avg_fitness)

        # Surplus retention (sum of 1-T = sum of fitness)
        surplus_retention = sum(fitnesses)
        surplus_retentions.append(surplus_retention)

        # Adaptation speed (check if avg fitness > 0.9)
        if avg_fitness > 0.9 and len(adaptation_speeds) == 0:
            adaptation_speeds.append(gen)

        # Selection: top 50%
        sorted_agents = sorted(agents, key=lambda a: a.fitness(), reverse=True)
        survivors = sorted_agents[:group_size // 2]

        # Reproduce
        agents = survivors + [Agent(S=a.S, R=a.R) for a in survivors]

    return avg_fitnesses, surplus_retentions, adaptation_speeds

# Parameters
group_size = 1000
generations = 500
mutation_rate_base = 0.01
alpha = 5.0

print("=" * 60)
print("TENSION-DRIVEN MUTATION SIMULATION")
print("=" * 60)
print(f"\nParameters:")
print(f"  Population size: {group_size}")
print(f"  Generations: {generations}")
print(f"  Base mutation rate (μ_base): {mutation_rate_base}")
print(f"  Alpha (α): {alpha}")
print()

# Simulation for Tension-Driven Mutation group
print("Running Tension-Driven Mutation simulation...")
avg_fitnesses_tdm, surplus_tdm, adapt_tdm = simulate(group_size, generations, mutation_rate_base, alpha, variable_mutation=True)

# Simulation for Control Group (constant mutation rate)
print("Running Control Group simulation...")
avg_fitnesses_control, surplus_control, adapt_control = simulate(group_size, generations, mutation_rate_base, alpha, variable_mutation=False)

# Results
print("\n" + "=" * 60)
print("RESULTS")
print("=" * 60)

final_fitness_tdm = avg_fitnesses_tdm[-1]
final_fitness_control = avg_fitnesses_control[-1]
final_surplus_tdm = surplus_tdm[-1]
final_surplus_control = surplus_control[-1]

print(f"\nTension-Driven Mutation:")
print(f"  Final Average Fitness: {final_fitness_tdm:.4f}")
print(f"  Final Surplus Retention: {final_surplus_tdm:.1f}")
print(f"  Adaptation Speed: {'Gen ' + str(adapt_tdm[0]) if adapt_tdm else 'Not reached 0.9'}")

print(f"\nControl Group (Constant μ):")
print(f"  Final Average Fitness: {final_fitness_control:.4f}")
print(f"  Final Surplus Retention: {final_surplus_control:.1f}")
print(f"  Adaptation Speed: {'Gen ' + str(adapt_control[0]) if adapt_control else 'Not reached 0.9'}")

print("\n" + "-" * 60)
if final_surplus_tdm > final_surplus_control:
    print("✓ TENSION-DRIVEN MUTATION preserves more surplus!")
    print(f"  Advantage: {((final_surplus_tdm/final_surplus_control)-1)*100:.1f}% more surplus")
else:
    print("✗ Control Group preserves more surplus")
    print(f"  Difference: {((final_surplus_control/final_surplus_tdm)-1)*100:.1f}%")
print("-" * 60)

# Plotting
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Plot 1: Average Fitness
axes[0].plot(avg_fitnesses_tdm, label='Tension-Driven Mutation', color='blue')
axes[0].plot(avg_fitnesses_control, label='Control (Constant μ)', color='red', linestyle='--')
axes[0].set_xlabel('Generation')
axes[0].set_ylabel('Average Fitness')
axes[0].set_title('Average Fitness Over Generations')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

# Plot 2: Surplus Retention
axes[1].plot(surplus_tdm, label='Tension-Driven Mutation', color='blue')
axes[1].plot(surplus_control, label='Control (Constant μ)', color='red', linestyle='--')
axes[1].set_xlabel('Generation')
axes[1].set_ylabel('Surplus Retention (Σ Fitness)')
axes[1].set_title('Surplus Retention Over Generations')
axes[1].legend()
axes[1].grid(True, alpha=0.3)

plt.suptitle('DFA Tension-Driven Mutation Hypothesis Test', fontsize=14)
plt.tight_layout()
plt.savefig('/home/king/Downloads/documentsforgi/evidence/tension_mutation_simulation.png', dpi=150)
print(f"\nPlot saved to: evidence/tension_mutation_simulation.png")
plt.show()
